import { Article, Issue, Product, SubscriptionTier } from './types'

// Sample Articles Data
export const articles: Article[] = [
  {
    id: 1,
    title: "What Silicon Valley Bank's Collapse Teaches Us About Risk",
    excerpt: "When the bank collapsed in March 2023, it wasn't just a failure of risk management. It was a failure of imagination.",
    category: 'moment',
    date: 'February 15, 2026',
    readTime: '8 min read',
    tags: ['philosophy', 'risk', 'finance', 'stoicism'],
    poem: {
      title: 'Risk',
      lines: [
        "The ocean doesn't read your resume.",
        "It doesn't care about your credentials.",
        "It just is.",
        "",
        "Same with markets.",
        "Same with life.",
        "",
        "What you have today,",
        "you can lose tomorrow.",
        "What seems certain,",
        "is anything but.",
      ],
    },
    content: '',
  },
  {
    id: 2,
    title: 'The Psychology of Algorithms',
    excerpt: 'How recommendation engines shape what we believe, and why that matters for democracy.',
    category: 'current',
    date: 'February 12, 2026',
    readTime: '5 min read',
    tags: ['technology', 'psychology', 'democracy'],
    poem: {
      lines: [
        'The algorithm knows you better than you know yourself.',
        'Or so it claims.',
        '',
        'What it really knows:',
        'Your patterns.',
        'Your weaknesses.',
        'Your wants.',
        '',
        'Not your reasons.',
        'Not your values.',
        'Not your self.',
      ],
    },
    content: '',
  },
]

// Subscription Tiers
export const subscriptionTiers: SubscriptionTier[] = [
  {
    id: 'digital',
    name: 'Digital',
    price: { monthly: 10, yearly: 120 },
    description: 'For the digital reader',
    features: [
      'Full website access',
      'Digital magazine issues',
      'Weekly newsletter',
      'Early access to articles',
      'Downloadable poetry collections',
      'No ads',
      'Access to archives',
    ],
  },
  {
    id: 'print',
    name: 'Print + Digital',
    price: { monthly: 25, yearly: 250 },
    description: 'The complete experience',
    features: [
      'Everything in Digital',
      'Quarterly print magazine',
      'Print-only content',
      '10% shop discount',
      'Subscriber events',
    ],
    popular: true,
  },
  {
    id: 'founding',
    name: 'Founding Member',
    price: { yearly: 500 },
    description: 'Be part of the foundation',
    features: [
      'Everything in Print + Digital',
      'Signed editions',
      'Name in masthead',
      'Annual hardcover anthology',
      '20% shop discount',
      'Quarterly editor letter',
      'First access to special editions',
    ],
    limited: true,
  },
]

// Issues Data
export const issues: Issue[] = [
  {
    id: 1,
    title: 'Issue 1',
    subtitle: 'Winter 2026',
    season: 'Winter',
    year: '2026',
    description: 'Inaugural issue featuring risk, uncertainty, and the philosophy of finance.',
    articles: 12,
    pages: 72,
    price: 22,
    coverColor: 'from-green/20 to-green/10',
  },
  {
    id: 2,
    title: 'Issue 2',
    subtitle: 'Spring 2026',
    season: 'Spring',
    year: '2026',
    description: 'Essays on renewal, growth, and the philosophy of new beginnings.',
    articles: 11,
    pages: 68,
    price: 22,
    coverColor: 'from-amber-50 to-amber-100',
    upcoming: true,
  },
]

// Sample Products
export const products: Record<string, Product[]> = {
  magazines: [
    {
      id: 1,
      name: 'Issue 1: Winter 2026',
      price: 22,
      description: '72 pages, 12 articles',
      type: 'Print',
      category: 'magazines',
      images: [],
      inStock: true,
    },
    {
      id: 2,
      name: 'Annual Anthology 2025',
      price: 45,
      description: '200 pages, best of Year 1',
      type: 'Hardcover',
      category: 'magazines',
      images: [],
      inStock: true,
    },
  ],
  apparel: [
    {
      id: 3,
      name: 'The Subscriber Tee',
      price: 32,
      description: 'Cream with charcoal text',
      category: 'apparel',
      images: [],
      inStock: true,
    },
    {
      id: 4,
      name: 'Check Tee',
      price: 32,
      description: '"Check......" centered',
      category: 'apparel',
      images: [],
      inStock: true,
    },
    {
      id: 5,
      name: 'Signature Hoodie',
      price: 58,
      description: 'Minimal masthead design',
      category: 'apparel',
      images: [],
      inStock: true,
    },
  ],
  accessories: [
    {
      id: 6,
      name: 'Signature Tote',
      price: 25,
      description: 'Heavy canvas, 15" × 16"',
      category: 'accessories',
      images: [],
      inStock: true,
    },
    {
      id: 7,
      name: 'Coffee Mug',
      price: 18,
      description: '11oz ceramic, poem excerpt',
      category: 'accessories',
      images: [],
      inStock: true,
    },
    {
      id: 8,
      name: 'Philosophy Journal',
      price: 24,
      description: '160 pages, dotted',
      category: 'accessories',
      images: [],
      inStock: true,
    },
  ],
  prints: [
    {
      id: 9,
      name: 'Individual Poem Print',
      price: 28,
      description: '11" × 14", museum quality',
      category: 'prints',
      images: [],
      inStock: true,
    },
    {
      id: 10,
      name: 'Signed Print Set',
      price: 95,
      description: '3 poems, signed, limited',
      category: 'prints',
      images: [],
      inStock: true,
    },
  ],
}
